# Generated by Django 4.0.3 on 2022-04-03 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comunicados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_comunicado', models.CharField(max_length=300)),
                ('descricao_comunicado', models.TextField(max_length=300)),
                ('texto_comunicado', models.TextField()),
                ('data_comunicado', models.DateTimeField()),
            ],
        ),
    ]
