# Generated by Django 4.0.3 on 2022-04-03 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comunicados',
            new_name='Comunicado',
        ),
    ]
