# Generated by Django 4.0.3 on 2022-04-02 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acessos',
            fields=[
                ('nome_usuario', models.CharField(max_length=200)),
                ('email_usuario', models.CharField(max_length=200)),
                ('cpf_usuario', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('tipo_usuario', models.CharField(choices=[('Aluno', 'Aluno'), ('Professor', 'Professor'), ('Coordenador', 'Coordenador')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('nome_aluno', models.CharField(max_length=200)),
                ('email_aluno', models.CharField(max_length=200)),
                ('cpf_aluno', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('tipo_aluno', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Coordenador',
            fields=[
                ('nome_coordenador', models.CharField(max_length=200)),
                ('email_coordenador', models.CharField(max_length=200)),
                ('cpf_coordenador', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('tipo_coordenador', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('nome_professor', models.CharField(max_length=200)),
                ('email_professor', models.CharField(max_length=200)),
                ('cpf_professor', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('tipo_professor', models.CharField(max_length=100)),
            ],
        ),
    ]
