# Generated by Django 4.0.3 on 2022-04-01 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_aluno', models.CharField(max_length=200)),
                ('email_aluno', models.CharField(max_length=200)),
                ('cpf_aluno', models.IntegerField(default=0)),
                ('tipo_aluno', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Coordenador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_coordenador', models.CharField(max_length=200)),
                ('email_coordenador', models.CharField(max_length=200)),
                ('cpf_coordenador', models.IntegerField(default=0)),
                ('tipo_coordenador', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_professor', models.CharField(max_length=200)),
                ('email_professor', models.CharField(max_length=200)),
                ('cpf_professor', models.IntegerField(default=0)),
                ('tipo_professor', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='cpf_aluno',
            new_name='cpf_usuario',
        ),
        migrations.AddField(
            model_name='usuario',
            name='email_usuario',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
