# Generated by Django 4.0.3 on 2022-04-02 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acessos',
            name='cpf_usuario',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='acessos',
            name='email_usuario',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='cpf_aluno',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='email_aluno',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='coordenador',
            name='cpf_coordenador',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='coordenador',
            name='email_coordenador',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='professor',
            name='cpf_professor',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='professor',
            name='email_professor',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
