# Generated by Django 4.0.3 on 2022-04-01 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_aluno_coordenador_professor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='id',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='cpf_usuario',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
