# Generated by Django 4.0.3 on 2022-04-01 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_remove_usuario_id_alter_usuario_cpf_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='id',
        ),
        migrations.RemoveField(
            model_name='coordenador',
            name='id',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='id',
        ),
        migrations.AlterField(
            model_name='aluno',
            name='cpf_aluno',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='coordenador',
            name='cpf_coordenador',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='professor',
            name='cpf_professor',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
