# Generated by Django 4.0.3 on 2022-04-01 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_remove_aluno_id_remove_coordenador_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acessos',
            fields=[
                ('nome_usuario', models.CharField(max_length=200)),
                ('email_usuario', models.CharField(max_length=200)),
                ('cpf_usuario', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('tipo_usuario', models.CharField(choices=[(1, 'Aluno'), (2, 'Professor'), (3, 'Coordenador')], max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
