# Generated by Django 4.0.3 on 2022-04-01 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_acessos_delete_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acessos',
            name='tipo_usuario',
            field=models.CharField(choices=[('1', 'Aluno'), ('2', 'Professor'), ('3', 'Coordenador')], max_length=100),
        ),
    ]
