# Generated by Django 4.0.3 on 2022-04-01 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_alter_acessos_tipo_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acessos',
            name='tipo_usuario',
            field=models.CharField(choices=[('Aluno', 'Aluno'), ('Professor', 'Professor'), ('Coordenador', 'Coordenador')], max_length=100),
        ),
    ]
