# Generated by Django 4.0.3 on 2022-04-03 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acessos',
            fields=[
                ('nome_usuario', models.CharField(max_length=200)),
                ('email_usuario', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('cpf_usuario', models.IntegerField(default=0)),
                ('tipo_usuario', models.CharField(choices=[('Aluno', 'Aluno'), ('Professor', 'Professor'), ('Coordenador', 'Coordenador')], max_length=100)),
            ],
        ),
    ]
